- hosts: namenodeip
  vars_files:
     - namenode_vars.yml  
  tasks:
     - copy:
         src: "/root/jdk-8u171-linux-x64.rpm"
         dest: "/root/jdk-8u171-linux-x64.rpm"

     - copy:
         src: "/root/hadoop-1.2.1-1.x86_64.rpm"
         dest: "/root/hadoop-1.2.1-1.x86_64.rpm"

     - command:
         cmd: "rpm -ivh jdk-8u171-linux-x64.rpm --force"

     - command:
         cmd: "rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force"

     - lineinfile:
         path: "/etc/hadoop/hdfs-site.xml"
         regexp: '</configuration>'
         insertafter: '<configuration>'
         line: "<property>\n<name>dfs.name.dir</name>\n<value>{{ nn_dir }}</value>\n</property>\n</configuration>"

     - lineinfile:
         path: "/etc/hadoop/core-site.xml"
         regexp: '</configuration>'
         insertafter: '<configuration>'
         line: "<property>\n<name>fs.default.name</name>\n<value>hdfs://{{ ansible_facts['default_ipv4']['address'] }}:9001</value>\n</property>\n</configuration>"

     - file:
         state: directory
         path: "{{ nn_dir }}"

     - name: Stopping firewall
       shell: "systemctl stop firewalld"

     - name: Formatting namenode
       shell: "echo Y | hadoop namenode -format"
         
     - name: Starting namenode services
       shell: "hadoop-daemon.sh start namenode"
